algoritmo "soma2num"


var
     //Seção de Declaração de Variáveis

     A : inteiro
     B, C : inteiro



inicio
       //fase de entrada de dados

       //comando de saída de dados
       escreva("Digite um numero: ")
       
       //comando de entrada
       leia(A)
       
       escreva("Digite outro numero: ")
       leia(B)

       //processamento
       C <- A - B
       
       //fase saída de dddos
       escreva(C)

fimalgoritmo