Algoritmo "clpcc_aula_36_tabuada"

Var
     i, j : inteiro


Inicio
       //inicialização
       i <- 1
       
       enquanto i <= 10 faca
           para j de 1 ate 10 faca
                
           escreval(i, " X", j, " = ", i*j)
           
           fimpara
           escreval()
           
       //incremento
       i <- i + 1
       
       fimenquanto

Fimalgoritmo
