Algoritmo "clpcc_aula_38_lista_03_ex_02"

Var
   i, soma: inteiro

Inicio
      //inicialização
      i <- 1
      
      //parada
      enquanto i <= 100 faca
      
               soma <- soma + i
               escreval("Soma = ", soma)
               //incremento
               i <- i + 1
      fimenquanto
      
      escreval("Soma Final")
      escreval("Soma =", soma)

Fimalgoritmo
