algoritmo "divisores_aula12"

var

     //declaração das vriaveis
     a, b : inteiro
     divisao_int, resto : inteiro
     
     c, d : real
     divisao1, divisao2, divisao3 : real

inicio

     //tipo inteiro
     a <- 5
     b <- 2
     
     divisao_int <- a \ b
     resto <- a MOD b
     
     //tipo real
     c <- 5
     d <- 2
     
     divisao1 <- c / d
     divisao2 <- a / b
     divisao3 <- c \ d

fimalgoritmo
